# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.define :node01 do |node01|
    node01.vm.box = 'ubuntu16.04'
    node01.vm.box_url = 'http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box'
    node01.vm.hostname = 'node01'
    define_machine_name(node01)
    node01.vm.network :private_network, ip: '192.168.33.11' # NICが追加されている
    node01.vm.network :forwarded_port, guest: 22, host: 21_022, id: 'ssh'
    node01.vm.provision :ansible_local do |ansible|
      ansible.playbook = node01.vm.hostname + '/playbook.yaml'
    end
  end

  def define_machine_name(node)
    node.vm.provider :virtualbox do |vbox|
      vbox.name = node.vm.hostname
    end
  end
end
