---
- hosts: node02
  gather_facts: false
  become: true
  tasks:
  - name: install python-pip
    apt:
      name: "{{ packages }}"
      update_cache: true
      state: present
    vars:
      packages:
        - python-pip
